export const movies = [
    {
        id: 1,
        name: "The Shawshank Redemption",
        year: 1994,
        director: "Frank Darabont",
        rating: 9.3,
    },
    {
        id: 2,
        name: "The Godfather",
        year: 1972,
        director: "Francis Ford Coppola",
        rating: 9.2,
    },
    {
        id: 3,
        name: "The Dark Knight",
        year: 2008,
        director: "Christopher Nolan",
        rating: 9.0,
    },
    {
        id: 4,
        name: "Pulp Fiction",
        year: 1994,
        director: "Quentin Tarantino",
        rating: 8.9,
    },
    {
        id: 5,
        name: "The Lord of the Rings: The Return of the King",
        year: 2003,
        director: "Peter Jackson",
        rating: 8.9,
    },
    {
        id: 6,
        name: "Schindler's List",
        year: 1993,
        director: "Steven Spielberg",
        rating: 8.9,
    },
    {
        id: 7,
        name: "Fight Club",
        year: 1999,
        director: "David Fincher",
        rating: 8.8,
    },
    {
        id: 8,
        name: "Forrest Gump",
        year: 1994,
        director: "Robert Zemeckis",
        rating: 8.8,
    },
    {
        id: 9,
        name: "Inception",
        year: 2010,
        director: "Christopher Nolan",
        rating: 8.8,
    },
    {
        id: 10,
        name: "The Matrix",
        year: 1999,
        director: "Lana Wachowski, Lilly Wachowski",
        rating: 8.7,
    },
];
